version: "3.7"
services:
  postgres:
    image: postgres:14.10
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=recipes
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - "5432:5432"
    volumes:
      - ./db/postgres-test-data:/var/lib/postgresql/data
